# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/RMX1851/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),RMX1851)

include $(CLEAR_VARS)
LOCAL_MODULE := libqdMetaData
LOCAL_MODULE_OWNER := Realme
LOCAL_SRC_FILES_64 := proprietary/lib64/libqdMetaData.so
LOCAL_SRC_FILES_32 := proprietary/lib/libqdMetaData.so
LOCAL_MULTILIB := both
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_SUFFIX := .so
include $(BUILD_PREBUILT)

endif
